// Minimal GLAD C source stub
// In a real scenario, this file is generated by the GLAD web service
// and contains the OpenGL function pointer loading implementation.

#include <stdio.h> // For NULL if not defined
#include <glad/glad.h> // Include its own header

int gladLoadGLLoader(GLADloadproc loader) {
    // Stub implementation:
    // In a real GLAD file, this would load function pointers.
    // For a stub, we can just pretend it succeeded if a loader is provided.
    if (loader) {
        // Example: loader("glGetString"); // Try to load one function
        return 1; // Success
    }
    return 0; // Failure
}

// Minimal stub implementations for functions declared in glad.h
void glClear(GLenum mask) { (void)mask; /* no-op */ }
void glClearColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) { (void)red; (void)green; (void)blue; (void)alpha; /* no-op */ }
void glViewport(int x, int y, int width, int height) { (void)x; (void)y; (void)width; (void)height; /* no-op */ }

// ImGui might call glGetString(GL_VERSION) or similar during init
const char* glGetString(GLenum name) {
    (void)name;
    // Return a dummy version string or similar if needed
    // For example, if name == GL_VERSION (0x1F02 according to gl.h)
    // if (name == 0x1F02) return (const char*)"3.3 Stubbed GLAD";
    return NULL;
}
